from enum import Enum, unique


@unique
class Strategy(Enum):
    FLASHSWAPBSC = "FLASHSWAPBSC"
    MULTICEXDEXBSCMEXCTAKER = "MULTICEXDEXBSCMEXCTAKER"


@unique
class Project(Enum):
    MEXCSPOTWSDATASERVICE = "MEXCSPOTWSDATASERVICE"


@unique
class RestEnum(Enum):
    BINANCESPOTSYNCH = "BINANCESPOTSYNCH"
    BINANCESPOTASYNCH = "BINANCESPOTASYNCH"
    BINANCESWAPUSDTSYNCH = "BINANCESWAPUSDTSYNCH"
    BINANCESWAPUSDTASYNCH = "BINANCESWAPUSDTASYNCH"

    MEXCSPOTSYNCH = "MEXCSPOTSYNCH"
    MEXCSPOTASYNCH = "MEXCSPOTASYNCH"

    BSCDEXPOOL = "BSCDEXPOOL"
    BSCDEXPOOLASYNCH = "BSCDEXPOOLASYNCH"
    BSCDEXPOOLSYNCH = "BSCDEXPOOLSYNCH"
