from enum import Enum, unique


@unique
class RhinoSign(Enum):
    QD = "QD"
    MA = "MA"
    ATR = "ATR"
    KLINEDOWNTREND = "KLINEDOWNTREND"  # 根据 K 线下单
    KLINETRIANGLE = "KLINETRIANGLE"  # 根据 K 线下单


@unique
class RhinoDataType(Enum):
    QD = "QD"
    MA = "MA"
    ATR = "ATR"
    KLINEDOWNTREND = "KLINEDOWNTREND"
    KLINETRIANGLE = "KLINETRIANGLE"

    WEBSOCKETBREAK = "WEBSOCKETBREAK"
    WEBSOCKETSTART = "WEBSOCKETSTART"
    RHINODEPTH = "RHINODEPTH"
    RHINOTRADE = "RHINOTRADE"
    RHINOKLINE = "RHINOKLINE"
    RHINOTICKER = "RHINOTICKER"


@unique
class Strategy(Enum):
    FLASHSWAPBSC = "FLASHSWAPBSC"
    MULTICEXDEXBSCMEXCTAKER = "MULTICEXDEXBSCMEXCTAKER"
    USWAPLSHL = "USWAPLSHL"


@unique
class Project(Enum):
    MEXCSPOTWSDATASERVICE = "MEXCSPOTWSDATASERVICE"


@unique
class RestEnum(Enum):
    BINANCESPOTSYNCH = "BINANCESPOTSYNCH"
    BINANCESPOTASYNCH = "BINANCESPOTASYNCH"
    BINANCESWAPUSDTSYNCH = "BINANCESWAPUSDTSYNCH"
    BINANCESWAPUSDTASYNCH = "BINANCESWAPUSDTASYNCH"

    MEXCSPOTSYNCH = "MEXCSPOTSYNCH"
    MEXCSPOTASYNCH = "MEXCSPOTASYNCH"

    BSCDEXPOOL = "BSCDEXPOOL"
    BSCDEXPOOLASYNCH = "BSCDEXPOOLASYNCH"
    BSCDEXPOOLSYNCH = "BSCDEXPOOLSYNCH"


@unique
class MethodEnum(Enum):
    """
    和 BaseGateway 里面的函数相对应
    """
    # RhinoCollect 里面的
    GETDEPTHS = "GETDEPTHS"
    GETTRADES = "GETTRADES"
    GETKLINE = "GETLINE"
    GETTICKER = "GETTICKER"


@unique
class BarDirectionEnum(Enum):
    UP = "UP"
    DOWN = "DOWN"
    BOTH = "BOTH"
