from enum import Enum, unique


@unique
class Strategy(Enum):
    FLASHSWAPBSC = "FLASHSWAPBSC"
    MULTICEXDEXBSCMEXCTAKER = "MULTICEXDEXBSCMEXCTAKER"


@unique
class Project(Enum):
    MEXCSPOTWSDATASERVICE = "MEXCSPOTWSDATASERVICE"


@unique
class RestEnum(Enum):
    BINANCESPOTSYNCH = "BINANCESPOTSYNCH"
    BINANCESPOTASYNCH = "BINANCESPOTASYNCH"
    BINANCESWAPUSDTSYNCH = "BINANCESWAPUSDTSYNCH"
    BINANCESWAPUSDTASYNCH = "BINANCESWAPUSDTASYNCH"

    MEXCSPOTSYNCH = "MEXCSPOTSYNCH"
    MEXCSPOTASYNCH = "MEXCSPOTASYNCH"

    BSCDEXPOOL = "BSCDEXPOOL"
    BSCDEXPOOLASYNCH = "BSCDEXPOOLASYNCH"
    BSCDEXPOOLSYNCH = "BSCDEXPOOLSYNCH"


@unique
class MethodEnum(Enum):
    ACCOUNTBALANCE = "ACCOUNTBALANCE"
    SUBMITORDER = "SUBMITORDER"
    CANCELORDERID = "CANCELORDERID"  # 按照 order id 取消订单
    CANCELORDERSYMBOL = "CANCELORDERSYMBOL"
    WITHDRAW = "WITHDRAW"
    GETWITHDRAWSTATE = "GETWITHDRAWSTATE"
    GETTRADES = "GETTRADES"
    GETDEPTHS = "GETDEPTHS"
    GETPOSITIONS = "GETPOSITIONS"
    CLOSEPOSITION = "CLOSEPOSITION"
    UPDATELEVERAGE = "UPDATELEVERAGE"
    CLOSEORDER = "CLOSEORDER"
    BESTORDERDEPTH = "BESTORDERDEPTH"
    GETCOINSINFOS = "GETCOINSINFOS"
